apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-pv
  labels:
    app: todoapp
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/todoapp-pv        # локальний шлях на ноді (Docker Desktop/KinD/minikube)
